name: Node.js DEMO CI/CD

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ‚¨áÔ∏è Checkout code
        uses: actions/checkout@v3

      - name: üöÄ Deploy using rsync
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            rsync -avz --delete \
              --exclude=".env" \
              --exclude="node_modules" \
              --exclude=".git" \
              $GITHUB_WORKSPACE/ \
              /var/www/gitrepo/node-express-mongo-mysql/

      - name: üîÅ SSH into server and restart PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            cd /var/www/gitrepo/node-express-mongo-mysql

            # Node dependencies
            npm install --omit=dev

            # Restart server
            pm2 reload node-express-mongo-mysql --update-env || pm2 start server.js --name node-express-mongo-mysql
            pm2 save