name: Node.js DEMO CI/CD

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      
    - name: ğŸ”‘ Load SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: ğŸš€ Deploy using rsync
      run: |
        rsync -avz --delete \
          --exclude=".env" \
          --exclude="node_modules" \
          --exclude=".git" \
          -e "ssh -p 22 -o StrictHostKeyChecking=no" \
          ./ \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/gitrepo/node-express-mongo-mysql/

    - name: ğŸ” Restart PM2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/gitrepo/node-express-mongo-mysql
          npm install --omit=dev
          pm2 reload node-express-mongo-mysql --update-env || \
          pm2 start server.js --name node-express-mongo-mysql
          pm2 save